# Generated by Django 3.0.5 on 2020-12-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0006_auto_20201226_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
