# Generated by Django 3.0.5 on 2020-12-26 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_tweetmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TweetManager',
        ),
    ]
